textures:
  - 'public/textures/**/*'

audio:
  - 'public/audio/**/*'

typescript:
  - '**/*.ts'

scss:
  - '**/*.scss'

universe:
  - 'src/addons/locations/**/*'

status:
  - 'src/addons/status/**/*'

ship:
  - 'src/addons/ship/**/*'

humanoids:
  - 'src/addons/humanoid/**/*'

json:
  - 'src/json/**'

tests:
  - 'tests/**'
